version: '3.9'
services:
  database:
    container_name: database
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    networks:
      - local

networks:
  local:
    name: jobservice